const cfg=window.COPAHUE_CONFIG||{},form=document.querySelector('#survey'),steps=[...document.querySelectorAll('.step')],nav=document.querySelector('#steps');let current=0;
const services=['Consulta médica','Consulta enfermería','Informes','Hidromasaje','Hidropulsor','Vapor','Nebulizaciones','Laguna del Chancho','Laguna verde','Fangoterapia total','Fangoterapia local','Hubbard con kinesiología','Kinesiología y fisioterapia','Oclusivos','Jornada dermatológica media','Jornada dermatológica completa','Gimnasio','Masaje total','Masaje local','Masaje geotermal','Máscara facial','Belleza facial integral','Belleza corporal integral','Tratamiento capilar','Spa de manos','Piernas cansadas','Anticelulítico','Circuito baño 3','Inmersión'];
const destination=['Alojamiento','Comidas y restaurant','Mantenimiento y limpieza de la localidad','Estado de atractivos','Atención y variedad en comercios','Información turística','Estado y señalización de los caminos','Conectividad (internet/teléfono/etc)'];
const ratings=[['NO UTILIZO','NU'],['MALO','M'],['REGULAR','R'],['BUENO','B'],['MUY BUENO','MB'],['EXCELENTE','E']];
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'').toLowerCase();
function ratingRows(items,prefix){return items.map(item=>`<div class="rating-row"><span>${item}</span>${ratings.map(([v,s])=>`<label data-short="${s}" title="${v}"><input type="radio" name="${prefix}__${slug(item)}" value="${v}" aria-label="${item}: ${v}"></label>`).join('')}</div>`).join('')}
document.querySelector('#services').innerHTML=ratingRows(services,'servicio');document.querySelector('#destination').innerHTML=ratingRows(destination,'destino');
steps.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.ariaLabel=`Paso ${i+1}: ${s.dataset.title}`;nav.appendChild(b)});
const navButtons=[...nav.children],back=document.querySelector('#back'),next=document.querySelector('#next'),submit=document.querySelector('#submit');
function show(i){current=i;steps.forEach((s,j)=>s.classList.toggle('active',j===i));navButtons.forEach((b,j)=>{b.className=j<i?'done':j===i?'active':''});back.hidden=i===0;next.hidden=i===steps.length-1;submit.hidden=i!==steps.length-1;if(i===steps.length-1)summary();window.scrollTo({top:0,behavior:'smooth'})}
function validate(){const required=[...steps[current].querySelectorAll('[required]')];let ok=true;required.forEach(el=>{const valid=el.type==='radio'?[...steps[current].querySelectorAll(`[name="${el.name}"]`)].some(x=>x.checked):el.checkValidity();el.classList.toggle('invalid',!valid);if(!valid)ok=false});if(!ok)toast('Complete los campos obligatorios para continuar.');return ok}
next.onclick=()=>{if(validate())show(current+1)};back.onclick=()=>show(current-1);
function data(){const fd=new FormData(form),out={};for(const [k,v] of fd)out[k]=v;form.querySelectorAll('input[type=checkbox]').forEach(x=>out[x.name]=x.checked?1:0);out._id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;out._capturado_en=new Date().toISOString();out._dispositivo=navigator.userAgent;return out}
function summary(){const d=data();document.querySelector('#summary').innerHTML=`<div class="summary-card"><b>Encuestador/a</b><p>${d.encuestador||'—'} · ${d.fecha_hora||'—'}</p></div><div class="summary-card"><b>Visitante</b><p>${d.residencia||'—'} · ${d.primeraVisita==='Si'?'Primera visita':'Visitante recurrente'} · ${d.acompanamiento||'—'}</p></div><div class="summary-card"><b>Viaje</b><p>${d.alojamiento||'—'} · ${d.noches||'—'} noches · baños ${String(d.diasTermales||'—').toLowerCase()}</p></div>`}
const queue=()=>JSON.parse(localStorage.getItem('copahue_queue')||'[]');const saveQueue=q=>{localStorage.setItem('copahue_queue',JSON.stringify(q));queueUI()};
function queueUI(){document.querySelector('#queueCount').textContent=queue().length}function toast(t){const x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3200)}
async function send(payload){if(!cfg.sheetsWebAppUrl)throw new Error('CONFIG');const res=await fetch(cfg.sheetsWebAppUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('HTTP');return res}
async function sync(){if(!navigator.onLine)return toast('Sin conexión: las respuestas permanecen guardadas.');let q=queue();if(!q.length)return toast('No hay respuestas pendientes.');const pending=[];for(const item of q){try{await send(item)}catch{pending.push(item)}}saveQueue(pending);toast(pending.length?`${pending.length} respuestas siguen pendientes.`:'Sincronización completa.')}
form.onsubmit=async e=>{e.preventDefault();if(!validate())return;const payload=data();try{await send(payload);toast('Encuesta guardada en la planilla.')}catch(err){const q=queue();q.push(payload);saveQueue(q);toast(err.message==='CONFIG'?'Encuesta guardada localmente. Falta configurar Google Sheets.':'Sin conexión: encuesta guardada en el dispositivo.')}const interviewer=form.encuestador.value;form.reset();form.encuestador.value=interviewer;form.fecha_hora.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);show(0)};
function connection(){const on=navigator.onLine;document.querySelector('#connectionDot').className=on?'online':'offline';document.querySelector('#connectionText').textContent=on?'Con conexión':'Modo sin conexión'}
document.querySelector('#syncButton').onclick=sync;addEventListener('online',()=>{connection();sync()});addEventListener('offline',connection);connection();queueUI();form.fecha_hora.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);show(0);
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
